version: '3'
services:
  jupyter-server:
    # build:
    #   context: ./jupyter-image
    image: cenotelie/jupyter-kernel-rust:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "./jupyter-config:/home/builder/.jupyter"
      - "./modules:/home/builder/notebooks"
    environment:
      HOME: /home/builder
    working_dir: /home/builder/notebooks
    stdin_open: true
    tty: true
    command: jupyter notebook --ip=0.0.0.0 --no-browser
