[package]
name = "aquarium"
version = "0.1.0"
authors = ["Laurent Wouters <lwouters@cenotelie.fr>"]
edition = "2021"

[dependencies]
rand = "0.8"
clap = "4"
serde = "1"
serde_derive = "1"
serde_json = "1"
