[package]
name = "libgeo-rust"
version = "0.1.0"
authors = ["Laurent Wouters <lwouters@cenotelie.fr>"]
edition = "2021"
build = "build.rs"

[build-dependencies]
bindgen = "0.59"
cc = "1"

[dependencies]
