[package]
name = "mymacro_derive"
version = "0.1.0"
authors = ["Laurent Wouters <lwouters@cenotelie.fr>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
mymacro = { path="../mymacro" }
proc-macro2 = "1"
syn = "1"
quote = "1"